# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- none

pool:
  vmImage: windows-latest

steps:
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'all'
    subscriptionId: 'c7d4ef2e-d5ee-4cd2-b88c-c435f6281b52'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'mytest'
    location: 'East Us'
    templateLocation: 'Linked artifact'
    csmFile: '$(Build.SourcesDirectory)/SQL/template.json'
    csmParametersFile: '$(Build.SourcesDirectory)/SQL/parameters.json'
    deploymentMode: 'Incremental'

- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'all'
    subscriptionId: 'c7d4ef2e-d5ee-4cd2-b88c-c435f6281b52'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'mytest'
    location: 'East US'
    templateLocation: 'Linked artifact'
    csmFile: '$(Build.SourcesDirectory)/webapp/template.json'
    csmParametersFile: '$(Build.SourcesDirectory)/webapp/parameters.json'
    deploymentMode: 'Incremental'